swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=\"alert(localStorage.getItem('authorized'))\" src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  /accounts/groupid/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccountById
      summary: Finds an account by ID
definitions:
  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic



